# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=1024)),
                ('expire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('type', models.CharField(choices=[('VE', 'Vegeterian'), ('VG', 'Vegan'), ('NO', 'Ordinary')], default='NO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('items', models.ManyToManyField(to='foodsharing.FoodInstance')),
            ],
        ),
        migrations.CreateModel(
            name='UserPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodsharing.Supply')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodsharing.UserPerson')),
            ],
        ),
        migrations.AddField(
            model_name='supply',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodsharing.UserPerson'),
        ),
        migrations.AddField(
            model_name='foodinstance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodsharing.FoodType'),
        ),
    ]
