# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsharing', '0003_auto_20171022_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='pretamanger',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
