# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('foodsharing', '0004_foodtype_pretamanger'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperson',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_history', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userperson',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userperson',
            name='rating_history',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='foodinstance',
            index=models.Index(fields=['expire_date'], name='foodsharing_expire__1963da_idx'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['date'], name='foodsharing_date_8fa356_idx'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['latitude', 'longitude'], name='foodsharing_latitud_e48b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='usersuggestion',
            index=models.Index(fields=['date'], name='foodsharing_date_f5ee4a_idx'),
        ),
    ]
