# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('foodsharing', '0005_auto_20171030_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterModelOptions(
            name='foodinstance',
            options={'verbose_name': '\u044d\u043a\u0437\u0435\u043c\u043f\u043b\u044f\u0440 \u0435\u0434\u044b', 'verbose_name_plural': '\u044d\u043a\u0437\u0435\u043c\u043f\u043b\u044f\u0440\u044b \u0435\u0434\u044b'},
        ),
        migrations.AlterModelOptions(
            name='foodtype',
            options={'verbose_name': '\u0442\u0438\u043f \u0435\u0434\u044b', 'verbose_name_plural': '\u0442\u0438\u043f\u044b \u0435\u0434\u044b'},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name': '\u043f\u043e\u0441\u0442\u0430\u0432\u043a\u0430', 'verbose_name_plural': '\u043f\u043e\u0441\u0442\u0430\u0432\u043a\u0438'},
        ),
        migrations.AlterModelOptions(
            name='userperson',
            options={'verbose_name': '\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c', 'verbose_name_plural': '\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0438'},
        ),
        migrations.AlterModelOptions(
            name='usersuggestion',
            options={'verbose_name': '\u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435', 'verbose_name_plural': '\u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f'},
        ),
        migrations.RemoveField(
            model_name='supply',
            name='items',
        ),
        migrations.RemoveField(
            model_name='userperson',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userperson',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='userperson',
            name='rating_history',
        ),
        migrations.AddField(
            model_name='foodinstance',
            name='supply',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='foodsharing.Supply'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodsharing.UserPerson'),
        ),
    ]
