# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodsharing', '0007_auto_20171106_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
