# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodsharing', '0008_auto_20171106_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinstance',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='foodsharing.FoodType'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='foodsharing.UserPerson'),
        ),
        migrations.AlterField(
            model_name='usersuggestion',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='foodsharing.UserPerson'),
        ),
    ]
