# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodsharing', '0011_vote'),
    ]

    operations = [
    ]
