# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodsharing', '0012_auto_20171114_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodinstance',
            name='ftype',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='foodsharing.FoodType'),
        ),
        migrations.AlterField(
            model_name='foodinstance',
            name='type',
            field=models.FloatField(default=0),
        ),
    ]
