# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsharing', '0013_auto_20171114_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
